### PR TITLE
WIP: Add showCreateRelationButton

### PR DESCRIPTION
**Pull request by cwilby**
Currently testing on a project, need to fix styling and review/refactor.

### CODE REVIEW

**Comment by LorenzoSapora** [comment]
Oh nice. @cwilby did you ever look into finishing this?

**Comment by cwilby** [comment]
@LorenzoSapora just did - thanks for the reminder! 👍

@orlyapps this is ready to be reviewed/merged - I wrapped the input in `flex align-center` to adhere to Nova's `showCreateRelationButton`, and refactored to hide the button in modals as per Nova convention.

Kapture 2020-12-13 at 17 06 09

**Comment by orlyapps** [comment]
@cwilby Awesome. Big Thanks and merged!

**Comment by HeinrichJulian** [comment]
@cwilby After actually creating a new related entry, I'm getting a JavaScript Error:

`TypeError: this.getAvailableResources is not a function`

Because of that error the newly created entry is also not preset and I have to refresh the page in order to select the new option.
Not sure if this is a bug in the code or if I'm missing something. Any ideas ??

**Comment by cwilby** [comment]
Definitely most likely a bug in the code.  I'll look into it today/tomorrow.

**Pull request merged**
